kind: pipeline
name: default
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/oil_monitor
      tags: latest
      build_args: BUILDKIT_INLINE_CACHE=1

trigger:
  ref:
    - refs/heads/main
